server:
  port: 8888
spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  #  profiles:
#    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: file:///${user.home}/Desktop/SpringStudy/servlet
        git:
#          uri: file:///C:/Users/YBS/Desktop/SpringStudy/servlet/applicaltion-yml-repo/
          uri: https://github.com/ybs1121/msa-application-yml
          default-label: master
#          password:
#          username: [my username]
#          password: [my password]
management:
  endpoints:
    web:
      exposure:
        include: health,busrefresh
